# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scout_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='giay_trai',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='scout_profile',
            name='khan_hang_nhi',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='scout_profile',
            name='khan_tan_sinh',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 14, 10, 56, 29, 898693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camp',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 14, 10, 56, 29, 898693, tzinfo=utc)),
        ),
    ]
