# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scout_info', '0002_auto_20160614_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 18, 3, 59, 1, 75291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camp',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 18, 3, 59, 1, 75291, tzinfo=utc)),
        ),
    ]
