# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0017_auto_20160706_1852'),
        ('scout_info', '0007_auto_20160705_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=200, null=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2016, 7, 6, 11, 52, 25, 234486, tzinfo=utc))),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 6, 11, 52, 25, 230485, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camp',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 6, 11, 52, 25, 230485, tzinfo=utc)),
        ),
    ]
