# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 04:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scout_info', '0008_auto_20160706_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 11, 4, 33, 40, 530030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camp',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 11, 4, 33, 40, 530030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 4, 33, 40, 542031, tzinfo=utc)),
        ),
    ]
