# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scout_info', '0009_auto_20160711_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='comment',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 12, 14, 49, 44, 901926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camp',
            name='giay_trai',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 12, 14, 49, 44, 901926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 14, 49, 44, 912940, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scout_profile',
            name='khan_hang_nhi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scout_profile',
            name='khan_tan_sinh',
            field=models.URLField(blank=True, null=True),
        ),
    ]
