# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scout_info', '0014_auto_20160717_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout_profile',
            name='hang_nhi_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 7, 13, 29, 400619, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='scout_profile',
            name='khan_quang_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 7, 13, 29, 400619, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='scout_profile',
            name='tan_sinh_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 19, 7, 13, 29, 400619, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 19, 7, 13, 29, 405131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camp',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 19, 7, 13, 29, 405131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 7, 13, 29, 416130, tzinfo=utc)),
        ),
    ]
