# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scout_info', '0015_auto_20160719_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 20, 8, 40, 11, 100065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camp',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 20, 8, 40, 11, 100065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 8, 40, 11, 105580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scout_profile',
            name='hang_nhi_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 8, 40, 11, 98564, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='scout_profile',
            name='khan_quang_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 8, 40, 11, 98564, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='scout_profile',
            name='tan_sinh_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 20, 8, 40, 11, 98564, tzinfo=utc), null=True),
        ),
    ]
