# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('link', models.URLField(default='', max_length=2000)),
                ('date_taken', models.DateField(default=datetime.datetime(2016, 7, 20, 15, 18, 2, 862151, tzinfo=utc))),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
