# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 08:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2016, 5, 28, 8, 12, 19, 857187, tzinfo=utc))),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('birthday', models.DateField(default=datetime.datetime(2016, 5, 28, 8, 12, 19, 852684, tzinfo=utc))),
                ('address', models.CharField(default='', max_length=500, null=True)),
                ('facebook', models.CharField(default='', max_length=30, null=True)),
                ('dad_name', models.CharField(default='', max_length=40, null=True)),
                ('dad_phone', models.PositiveIntegerField(default=0, null=True)),
                ('mom_name', models.CharField(default='', max_length=40, null=True)),
                ('mom_phone', models.PositiveIntegerField(default=0, null=True)),
                ('home_phone', models.PositiveIntegerField(default=0, null=True)),
                ('current_grade', models.PositiveIntegerField(default=6)),
                ('current_school', models.CharField(default='', max_length=50, null='True')),
                ('health_info', models.CharField(default='', max_length=500, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=20)),
                ('slogan', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.Team'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.Member'),
        ),
    ]
