# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 28, 8, 48, 14, 368493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 5, 28, 8, 48, 14, 365491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team_management.Team'),
        ),
    ]
