# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0005_auto_20160528_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 28, 11, 39, 16, 700410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 5, 28, 11, 39, 16, 692410, tzinfo=utc)),
        ),
    ]
