# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0007_auto_20160528_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 31, 16, 48, 57, 334782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 5, 31, 16, 48, 57, 331280, tzinfo=utc)),
        ),
    ]
