# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0011_auto_20160614_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 18, 3, 59, 1, 59666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 6, 18, 3, 59, 1, 59666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 18, 3, 59, 1, 59666, tzinfo=utc)),
        ),
    ]
