# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 04:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0017_auto_20160706_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 4, 33, 40, 518029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 7, 11, 4, 33, 40, 510029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 11, 4, 33, 40, 510029, tzinfo=utc)),
        ),
    ]
