# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0022_auto_20160716_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_leaders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 17, 15, 11, 51, 893218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 7, 17, 15, 11, 51, 885216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2016, 7, 17, 15, 11, 51, 889217, tzinfo=utc)),
        ),
    ]
